config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("modules.accounts.urls")),
    path("", include("modules.inventory.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]


admin.site.site_header = "Dj Starter Admin"
admin.site.site_title = "Dj Starter Admin Portal"
admin.site.index_title = "Welcome to Dj Starter Portal"

old/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views
from accounts.views import dealerSignupView, adminSignupView, customerSignupView

app_name = "accounts"
urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
    path("signup/", dealerSignupView.as_view(), name="dealerSignup"),
    path("customer/signup/", customerSignupView.as_view(), name="customerSignup"),
    path("administrator/signup/", adminSignupView.as_view(), name="adminSignup"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    # Password Reset
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            success_url="/accounts/password_reset/done/",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="accounts/password_reset_subject.txt",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/reset/done/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # Profile
    path("farmer/profile/", views.Farmer_Profile_View, name="farmerProfile"),
    path("customer/profile/", views.Customer_Profile_View, name="customerProfile"),
    path(
        "administrator/profile/",
        views.administrator_Profile_View,
        name="administratorProfile",
    ),
]

old/farmers/urls.py
from django.urls import path
from farmers import views

app_name = "farmers"

urlpatterns = [
    path("", views.homeView, name="home"),
    path("post/products/", views.productAddView, name="product_add"),
    path("farmer/<username>/details/",
         views.dealersDetailsView, name="dealersDetails"),
    path(
        "category/<str:category>/",
        views.CategoryFilterView, name="categoryFilter"
    ),
    path('farmer/rating', views.rateFarmer, name="rateFarmer"),
]

old/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("farmers.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

old/farmers/forms.py
from django import forms
# from farmers.models import Product
from accounts.models import Dealer, Product


class ProductAddForm(forms.ModelForm):
    description = forms.CharField(label="Description",
                                  widget=forms.Textarea(attrs={
                                      "class": "form-control",
                                      "placeholder": "Brief description of your product",
                                      "rows": "6",
                                      "cols": "25"
                                  }))
    quantity = forms.CharField(
        label="Quantity",
        widget=forms.TextInput(attrs={
            "placeholder": "Number of Kgs available"
        })
    )
    price = forms.CharField(
        label="Price",
        widget=forms.NumberInput(attrs={
            "placeholder": "Price per Kg"
        })
    )
    item = forms.CharField(
        label="Product",
        widget=forms.NumberInput(attrs={
            "placeholder": "Name of your farm product"
        })
    )

    class Meta:
        model = Product
        fields = ("item", "price", "quantity",
                  "description", "image")


class FarmerCategoryForm(forms.ModelForm):
    category = forms.CharField(disabled=True,
                               help_text="You can change the category in your profile. ",
                               widget=forms.TextInput(attrs={'readonly': True})
                               )

    class Meta:
        model = Dealer
        fields = ('category',)

modules/accounts/api/views.py
import requests

from django.contrib.auth import get_user_model
from modules.accounts.permissions import IsSuperUser
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.viewsets import ModelViewSet
from rest_framework_simplejwt.tokens import RefreshToken

from rest_framework_simplejwt.exceptions import InvalidToken, TokenError
from django.core.exceptions import ValidationError
from modules.accounts.api.serializers import (
    LoginSerializer,
    RegisterSerializer,
    UserSerializer,
)
from django.core.validators import validate_email


User = get_user_model()


class LoginViewSet(ModelViewSet, TokenObtainPairView):
    """
    API endpoint for user login and obtaining access and refresh tokens.
    """

    serializer_class = LoginSerializer
    permission_classes = [AllowAny]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, context={"request": request}
        )
        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])
        except ValidationError as e:
            return Response(
                {"error": e.args[0]},
                status=status.HTTP_400_BAD_REQUEST,
            )
        return Response(serializer.validated_data, status=status.HTTP_200_OK)


class LogoutViewSet(ModelViewSet):
    """
    Logout view to invalidate the user's refresh token.
    """

    permission_classes = [IsAuthenticated]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        refresh_token = request.data.get("refresh_token")

        if not refresh_token:
            return Response(
                {"error": "Refresh token is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            # Blacklist the refresh token, making it invalid
            token = RefreshToken(refresh_token)
            token.blacklist()
            return Response(
                {"success": "User was successfully logged out."},
                status=status.HTTP_200_OK,
            )
        except Exception as e:
            return Response(
                {"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )


class RefreshViewSet(ModelViewSet, TokenRefreshView):
    """
    Endpoint allows all users to refresh their token,
    by passing the refresh token in order to get a new access token
    """

    permission_classes = (AllowAny,)
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)

        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])

        return Response(serializer.validated_data, status=status.HTTP_200_OK)


class RegisterViewSet(ModelViewSet):
    """
    ViewSet for user registration.

    Allows users to register by providing necessary information
    such as phone number, email, name, and password.
    """

    serializer_class = RegisterSerializer
    permission_classes = [AllowAny]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        context = {"request": request}
        serializer = self.get_serializer(data=request.data, context=context)
        serializer.is_valid(raise_exception=True)

        try:
            user = serializer.save()
            refresh = RefreshToken.for_user(user)

            response_data = {
                "user": serializer.data,
                "access_token": str(refresh.access_token),
                "refresh_token": str(refresh),
            }

            return Response(response_data, status=status.HTTP_201_CREATED)
        except ValidationError as e:
            return Response(
                {"error": str(e)},
                status=status.HTTP_400_BAD_REQUEST,
            )


# Google Login
# https://www.googleapis.com/auth/userinfo.email
# https://developers.google.com/oauthplayground/
class GoogleSocialLoginViewSet(ModelViewSet):
    """
    Google Social Login, Use the url below to test the endpoint;
    https://www.googleapis.com/auth/userinfo.email
    https://developers.google.com/oauthplayground/
    return access_token from the url above
    """

    permission_classes = [AllowAny]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        token = request.data.get("token")

        if not token:
            return Response(
                {"error": "Token is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            response = requests.get(
                "https://www.googleapis.com/oauth2/v2/userinfo",
                params={"access_token": token},
            )
            response.raise_for_status()
            response_data = response.json()

            email = response_data.get("email")
            if not email:
                return Response(
                    {"error": "Email not provided by Google"},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            # Validate email address format
            try:
                validate_email(email)
            except ValidationError:
                return Response(
                    {"error": "Invalid email address"},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            user, created = User.objects.get_or_create(email=email)
            if created:
                user.full_name = response_data.get("name", "")
                user.is_active = True
                user.set_unusable_password()
                user.save()

            token = RefreshToken.for_user(user)
            return Response(
                {
                    "refresh": str(token),
                    "access": str(token.access_token),
                },
                status=status.HTTP_200_OK,
            )
        except requests.HTTPError as e:
            return Response(
                {"error": f"Google API request failed: {e.response.text}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )


class UserViewSet(ModelViewSet):
    """
    API endpoint that allows users to be viewed, created, updated, or deleted.
    """

    serializer_class = UserSerializer
    queryset = User.objects.all()
    permission_classes = [IsAuthenticated, IsSuperUser]
    http_method_names = ["get", "post", "put", "patch", "delete"]

modules/accounts/views.py
from django.shortcuts import render
from modules.accounts.decorators import customer_required, farmer_required

from modules.accounts.models import Customer, Farmer, RoleChoices, User
from django.views.generic import CreateView
from modules.accounts.forms import (
    CustomerProfileUpdateForm,
    FarmerProfileUpdateForm,
    FarmerSignupForm,
    UserSignupForm,
    UserUpdateForm,
)
from modules.accounts.send_mails import send_activation_mail
from django.contrib.auth import login
from modules.accounts.tokens import account_activation_token
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect


class FarmerSignupView(CreateView):
    """
    View for farmer registration/signup.

    Attributes:
        model (User): The User model to be used for registration.
        form_class (FarmerSignupForm): The form class for farmer registration.
        template_name (str): The HTML template to render for the registration page.
    """

    model = User
    form_class = FarmerSignupForm
    template_name = "accounts/farmerSignup.html"

    def get_context_data(self, **kwargs):
        """
        Get additional context data to be passed to the template.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            dict: The context data.
        """
        kwargs["user_type"] = RoleChoices.FARMER
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        """
        Handle a valid form submission.

        Save the user, send an activation email, and render a success template.

        Args:
            form (FarmerSignupForm): The form instance.

        Returns:
            HttpResponse: The response object rendering the success template.
        """
        user = form.save(commit=False)
        user.save()
        # send_activation_mail(user, self.request)

        return render(self.request, "accounts/sign_alert.html")


class CustomerSignupView(CreateView):
    model = User
    form_class = UserSignupForm
    template_name = "accounts/customerSignup.html"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = RoleChoices.CUSTOMER
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            # send_activation_mail(user, self.request)
        return render(self.request, "accounts/sign_alert.html")


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)

    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return render(request, "accounts/activate_success.html")
    else:
        return render(request, "accounts/activate_fail.html")


@login_required
@farmer_required
def FarmerProfileView(request):
    farmer = Farmer.objects.get(user=request.user)
    form = FarmerProfileUpdateForm(instance=farmer)
    user_form = UserUpdateForm(instance=request.user)

    if request.method == "POST":
        form = FarmerProfileUpdateForm(
            request.POST or None, request.FILES or None, instance=farmer
        )
        user_form = UserUpdateForm(
            request.POST or None, request.FILES or None, instance=request.user
        )
        if form.is_valid() and user_form.is_valid():
            form.save()
            user_form.save()
            messages.success(request, "Profile successfully updated.")
            return HttpResponseRedirect("/accounts/farmer/profile/")
    context = {"form": form, "userForm": user_form, "dealer": farmer}
    return render(request, "accounts/farmerProfile.html", context)


@login_required
@customer_required
def CustomerProfileView(request):
    customer = Customer.objects.get(user=request.user)
    form = CustomerProfileUpdateForm(instance=customer)
    user_form = UserUpdateForm(instance=request.user)

    if request.method == "POST":
        form = CustomerProfileUpdateForm(
            request.POST or None, request.FILES or None, instance=customer
        )

        user_form = UserUpdateForm(
            request.POST or None, request.FILES or None, instance=request.user
        )
        if form.is_valid() and user_form.is_valid():
            form.save()
            user_form.save()
            messages.success(request, "Profile successfully updated.")
            return HttpResponseRedirect("/accounts/customer/profile/")

    context = {"form": form, "userForm": user_form, "customerQs": customer}
    return render(request, "accounts/customerProfile.html", context)

old/templates/accounts/activate_email.html
{%autoescape off%} Welcome To Racky. Hi {{user.username}}, Please click on the
link below to confirm your email, http://{{domain}}{%url 'accounts:activate'
uidb64=uid token=token%} Thanks, The Rackey Team. {%endautoescape%}

old/templates/accounts/activate_success.html
{%extends 'accounts/main.html'%}
<!---->
{%load static%}
<!---->
{%block title%} Activateion Success {%endblock%}
<!---->
{%block content%}
<div class="container" align="center">
  <div class="alert alert-success text-left mt-4">
    Your account was successfully verified, you can now login to your Rackey
    account. Go to the <a href="{%url 'accounts:login'%}">Login Page</a>
  </div>
</div>
{%endblock%}

old/templates/accounts/adminSignup.html
{%extends 'accounts/main.html'%}
<!---->
{%load static%}{%load crispy_forms_tags%} {% load widget_tweaks %}
<!---->
{%block title%} Admin Signup {%endblock%}
<!---->
{%block content%}
<div class="container mt-3 margin-auto" style="margin: auto">
  <div class="row text-left">
    <div class="col-md-2"></div>
    <div class="col-md-8 ftco-animate">
      <div class="job-post-item p-4 d-block d-lg-flex" align="center">
        <div class="col-sm-12">
          <h3 class="text-left">Administrator Register,</h3>
          <p class="text-left" style="margin: 0; padding-bottom: 1">
            Description
          </p>
          <hr />
          <form action="#" method="post" class="text-left">
            {%csrf_token%}
            <!---->
            {% for field in form.visible_fields %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:'form-control' }}
              <!---->
              {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
              {% endfor %}
            </div>
            {% endfor %}
            <button
              class="btn btn-lg text-white col-sm-4 mt-4"
              style="background-color: #206dfb"
              type="submit"
            >
              Register
            </button>
            <br />
          </form>
          <p class="text-left mt-3">
            <a href="{%url 'accounts:password_reset'%}" class="text-left ml-1"
              >Forgot Password?</a
            >
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>
{%endblock%}

old/templates/accounts/administratorProfile.html
{%extends 'accounts/index.html'%}
<!---->
{%load crispy_forms_tags%}
<!---->
{%block title%} Signup {%endblock%}
<!---->
{%block content%}
<div class="container">
  <div class="row mt-3">
    <div class="col-sm-4">
      <div class="col-md-12 p-3 bg-white mb-3" align="center">
        <div class="card border-white align-items-center" align="center">
          <img class="rounded-circle" src="" height="150" width="150" alt="" />
          <div class="mt-3">
            <h4></h4>
            <p class="text-secondary"></p>
            <a href=""
              ><button class="btn btn-outline-primary">View Products</button></a
            >
          </div>
        </div>
      </div>
      <div class="col-md-12 p-3 bg-white" align="center">
        <div class="card border-success">
          <ul class="list-group list-group-flush">
            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Username</h6>
              <span class="text-secondary"></span>
            </li>
            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Name</h6>
              <span class="text-secondary"> </span>
            </li>
            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Email</h6>
              <span class="text-secondary"></span>
            </li>

            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Phone</h6>
              <span class="text-secondary"></span>
            </li>

            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Location</h6>
              <span class="text-secondary"></span>
            </li>

            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Category</h6>
              <span class="text-secondary"></span>
            </li>
            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Derivery</h6>
              <span class="text-secondary"></span>
            </li>

            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Response Time</h6>
              <span class="text-secondary"></span>
            </li>

            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Price Range</h6>
              <span class="text-secondary"></span>
            </li>

            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Price Terms</h6>
              <span class="text-secondary"></span>
            </li>

            <li
              class="list-group-item d-flex justify-content-between align-items-center flex-wrap"
            >
              <h6 class="mb-0">Email Protection</h6>
              <span class="text-secondary">
                <i class="fa fa-check fa-lg text-success"></i>

                <i class="fa fa-times fa-lg text-danger"></i>
              </span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-8 text-left">
      <div class="p-4 mb-3 bg-white text-left">
        <legend class="mr-2">
          <i><b class="text-info">Update</b></i> Profile
        </legend>
        <form method="POST" action="" enctype="">
          {%csrf_token%}
          <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6"></div>
          </div>
          <button class="btn btn-outline-primary">Update Profile</button>
        </form>
      </div>
    </div>
  </div>
</div>

{%endblock%}

old/templates/accounts/customerSignup.html
{%extends 'accounts/main.html'%}
<!---->
{%load static%}{%load crispy_forms_tags%} {% load widget_tweaks %}
<!---->
{%block title%} Customer Signup {%endblock%}
<!---->
{%block content%}
<div class="container mt-3 margin-auto" style="margin: auto">
  <div class="row text-left">
    <div class="col-md-2"></div>

    <div class="col-md-8 ftco-animate">
      <div class="job-post-item p-4 d-block d-lg-flex" align="center">
        <div class="col-sm-12">
          <h3 class="text-left">Customer Signup,</h3>
          <p class="text-left" style="margin: 0; padding-bottom: 1">
            Description
          </p>
          <hr />
          <form action="#" method="post" class="text-left">
            {%csrf_token%}
            <!---->
            {% for field in form.visible_fields %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:'form-control' }}
              <!---->
              {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
              {% endfor %}
            </div>
            {% endfor %}
            <button
              class="btn btn-lg text-white col-sm-4 mt-4"
              style="background-color: #206dfb"
              type="submit"
            >
              Register
            </button>
            <br />
          </form>
          <p class="text-left mt-3">
            <a href="{%url 'accounts:password_reset'%}" class="text-left ml-1"
              >Forgot Password?</a
            >
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

{%endblock%}

old/templates/accounts/dealersProfile.html
{%extends 'accounts/index.html'%}
<!---->
{%load crispy_forms_tags%}
<!---->
{%block title%} Profile {%endblock%}
<!---->
{%block content%}
<div class="container">
  <div class="row mt-3">
    <div class="col-sm-9">
      <div class="col-md-12 p-3 bg-white mb-3 text-left">
        <legend class="mr-2">
          <i><b class="text-info">Add</b></i> Product
        </legend>
        <form
          action="."
          class="bg-white"
          method="POST"
          enctype="multipart/form-data"
        >
          {%csrf_token%}
          <button
            class="btn btn-lg text-white col-sm-3 mt-4"
            style="background-color: #206dfb"
            type="submit"
          >
            update Profile
          </button>
        </form>
      </div>
    </div>

    <div class="col-sm-3 text-left">
      <div class="p-4 mb-3 bg-white">
        <div class="row">
          <div class="col-sm-4">
            <img src="" height="100px" width="100px" alt="" />
          </div>
          <div class="col-sm-8">
            <b></b>
            <div class="ml-1 mt-2"></div>
          </div>
        </div>
        <hr />
        <h3 class="h5 text-black mb-3">Contact Info</h3>
        <p class="mb-0 font-weight-bold">Address</p>
        <p class="mb-4"></p>
        <p class="mb-0 font-weight-bold">Phone</p>
        <p class="mb-4"></p>

        <p class="mb-0 font-weight-bold">Email Address</p>
        <p class="mb-0"></p>
      </div>
      <div class="p-4 mb-3 bg-white">
        <h3 class="h5 text-black mb-3">More Info</h3>
        <p></p>
        <p href="#" class="btn btn-primary py-2 px-4">Learn More</p>
      </div>
    </div>
  </div>
</div>
{%endblock%}

old/templates/accounts/logout.html
{%extends 'accounts/main.html'%}
<!---->
{%load static%}{%load crispy_forms_tags%}
<!---->
{% load widget_tweaks %}
<!---->
{%block title%} Logout {%endblock%}
<!---->
{%block content%} {%endblock%}

old/templates/accounts/password_reset.html
{%extends 'accounts/main.html'%}{% load widget_tweaks %}
<!---->
{%load crispy_forms_tags%} {%load static%}
<!---->
{%block title%} Password Reset! {%endblock%}
<!---->
{%block content%}
<div class="container mt-3" align="center">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 ftco-animate">
      <div class="job-post-item p-4 d-block d-lg-flex" align="center">
        <div class="col-sm-12">
          <h3 class="text-left">Forgot Password?</h3>
          <hr />
          <form action="#" method="post" class="text-left">
            {%csrf_token%}
            <!---->
            {% for field in form.visible_fields %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{ field|add_class:'form-control' }}
              <!---->
              {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
              {% endfor %}
            </div>
            {% endfor %}
            <button
              class="btn btn-lg text-white col-sm-4 mt-4"
              style="background-color: #206dfb"
              type="submit"
            >
              Password Reset
            </button>
            <br />
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>
{%endblock%}

old/templates/accounts/password_reset_complete.html
{%extends 'accounts/main.html'%}
<!---->
{%load static%}
<!---->
{%block title%} Password Reset Completed {%endblock%}
<!---->
{%block content%}
<div class="alert alert-success text-left">
  Password Reset was successfully Completed. Go to the
  <a href="{%url 'accounts:login'%}">Login Page</a>
</div>
{%endblock%}

old/templates/accounts/password_reset_confirm.html
{%extends 'accounts/main.html'%}
<!---->
{%load static%} {%load crispy_forms_tags%}
<!---->
{%block title%} Password Reset Confirm {%endblock%}
<!---->
{%block content%}
<h3>Reset Password</h3>
<hr />
<form method="POST" action="" enctype="multipart/form-data">
  {%csrf_token%} {{form.error}} {{form|crispy}}
  <button class="btn btn-outline-primary" type="submit">Reset</button>
</form>
{%endblock%}

old/templates/accounts/password_reset_done.html
{%extends 'accounts/main.html'%}
<!---->
{%load static%}
<!---->
{%block title%} Password Reset Done {%endblock%}
<!---->
{%block content%}
<div class="container">
  <br />
  <div class="alert alert-info text-center">
    We’ve emailed you with the instructions for resetting your password. If an
    account exists with the email you provided, you should receive an email
    shortly. If you don’t see the email in your inbox, please check your spam
    folder or contact the Rackey team.
  </div>
</div>
{%endblock%}

old/templates/accounts/password_reset_email.html
{% autoescape off %}
Hello {{user.get_username|title}},
You recently requested a password reset for your Account, click the link below to reset it:

{{protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token%}

If you did not request a password reset, Please ignore this mail
or reply to let us know.If clicking the link above doesn't work, please copy and
paste it in a new browsers tab.
Thanks, The Rackey Team.
{% endautoescape %}