config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("modules.accounts.urls")),
    path("", include("modules.inventory.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]


admin.site.site_header = "Dj Starter Admin"
admin.site.site_title = "Dj Starter Admin Portal"
admin.site.index_title = "Welcome to Dj Starter Portal"

old/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views
from accounts.views import dealerSignupView, adminSignupView, customerSignupView

app_name = "accounts"
urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
    path("signup/", dealerSignupView.as_view(), name="dealerSignup"),
    path("customer/signup/", customerSignupView.as_view(), name="customerSignup"),
    path("administrator/signup/", adminSignupView.as_view(), name="adminSignup"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    # Password Reset
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            success_url="/accounts/password_reset/done/",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="accounts/password_reset_subject.txt",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/reset/done/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # Profile
    path("farmer/profile/", views.Farmer_Profile_View, name="farmerProfile"),
    path("customer/profile/", views.Customer_Profile_View, name="customerProfile"),
    path(
        "administrator/profile/",
        views.administrator_Profile_View,
        name="administratorProfile",
    ),
]

old/farmers/urls.py
from django.urls import path
from farmers import views

app_name = "farmers"

urlpatterns = [
    path("", views.homeView, name="home"),
    path("post/products/", views.productAddView, name="product_add"),
    path("farmer/<username>/details/",
         views.dealersDetailsView, name="dealersDetails"),
    path(
        "category/<str:category>/",
        views.CategoryFilterView, name="categoryFilter"
    ),
    path('farmer/rating', views.rateFarmer, name="rateFarmer"),
]

old/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("farmers.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

old/accounts/forms.py
from unicodedata import category
from django import forms
from accounts.models import User, Administrator, Dealer, Customer,Counties
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.db import transaction
from django.forms import ModelForm
from farmers.models import ProductCategory


class UserSignUpForm(ModelForm):
    email = forms.EmailField(max_length=156, required=True)
    phone = forms.CharField(max_length=20, required=True)

    class Meta:
        model = User
        fields = ('username', "phone", 'email')

    password1 = forms.CharField(
        label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password Confirmation",
        widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Password don\'t match!')

        return password2

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = True
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()

        return user
class FarmerSignUpForm(ModelForm):
    email = forms.EmailField(max_length=156, required=True)
    phone = forms.CharField(max_length=20, required=True)
    category=forms.ModelChoiceField(
        queryset=ProductCategory.objects.all(),
        widget=forms.Select(),
        required=True
    )
    county=forms.ModelChoiceField(
        queryset=Counties.objects.all(),
        widget=forms.Select(),
        required=True
    )

    class Meta:
        model = User
        fields = ('username', "phone", 'email',"full_name")

    password1 = forms.CharField(
        label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password Confirmation",
        widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Password don\'t match!')

        return password2

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = True
        user.role="Dealer"
        user.set_password(self.cleaned_data["password1"])
        user.save()
        if commit:
            user.save()
        dealerQs=Dealer.objects.create(user=user,
        category=self.cleaned_data.get('category'),
        county=self.cleaned_data.get("county")
        )
        return user

class FarmerProfileUpdateForm(forms.ModelForm):
    bio = forms.CharField(label="Bio",
                          widget=forms.Textarea(attrs={
                              "class": "form-control",
                              "placeholder": "Briefly describe yourself",
                              "rows": "4",
                              "cols": "25"
                          }))

    class Meta:
        model = Dealer
        fields = ("category", "protect_email",
                  "derivery", "response", "county",
                  "town", "estate", "profile_picture",
                  "bio",
                  )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("full_name", "phone",)


class CustomerProfileUpdateForm(forms.ModelForm):
    bio = forms.CharField(label="Bio",
                          widget=forms.Textarea(attrs={
                              "class": "form-control",
                                "placeholder": "Briefly describe yourself",
                              "rows": "4",
                              "cols": "25"
                          }))

    class Meta:
        model = Customer
        fields = ("bio", "profile_picture",
                  "county", "town", "estate")

old/accounts/views.py
from calendar import c
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from accounts.models import User, Dealer, Customer
from accounts.decorators import (
    administrator_required, customer_required,
    dealer_required)
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core import serializers
from django.core.files.base import File
from django.core.mail import BadHeaderError, EmailMessage, send_mail
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.decorators.cache import never_cache
from django.views.generic import CreateView
from accounts.tokens import account_activation_token
from accounts.forms import UserSignUpForm
from accounts.sendMails import send_activation_mail
from accounts.forms import (FarmerProfileUpdateForm, UserUpdateForm,
 CustomerProfileUpdateForm,UserSignUpForm,
 FarmerSignUpForm)


def dealers_profile_view(request):
    context = {

    }
    return render(request, "accounts/dealersProfile.html", context)


class dealerSignupView(CreateView):
    model = User
    form_class = FarmerSignUpForm
    template_name = "accounts/dealerSignup.html"

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Dealer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        if form.is_valid():
            user = form.save(commit=False)
            user.role = "Dealer"
            user.save()
            send_activation_mail(user, self.request)
        return render(self.request, "accounts/sign_alert.html")


class adminSignupView(CreateView):
    model = User
    form_class = UserSignUpForm
    template_name = "accounts/adminSignup.html"

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Administrator'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        if form.is_valid():
            user = form.save(commit=False)
            user.is_admin = True
            user.is_staff = True
            user.role = "Administrator"
            user.save()
            send_activation_mail(user, self.request)
        return render(self.request, "accounts/sign_alert.html")


class customerSignupView(CreateView):
    model = User
    form_class = UserSignUpForm
    template_name = "accounts/customerSignup.html"

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Customer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        if form.is_valid():
            user = form.save(commit=False)
            user.role = "Customer"
            user.save()
            send_activation_mail(user, self.request)
        return render(self.request, "accounts/sign_alert.html")


@login_required
@dealer_required
def Farmer_Profile_View(request):
    dealerQs = Dealer.objects.get(user=request.user)
    form = FarmerProfileUpdateForm(instance=dealerQs)
    userForm = UserUpdateForm(instance=request.user)
    if request.method == "POST":
        form = FarmerProfileUpdateForm(
            request.POST or None,
            request.FILES or None,
            instance=dealerQs)
        userForm = UserUpdateForm(
            request.POST or None,
            request.FILES or None,
            instance=request.user
        )
        if form.is_valid() and userForm.is_valid():
            form.save()
            userForm.save()
            messages.success(request, "Profile successfully updated.")
            return HttpResponseRedirect("/accounts/farmer/profile/")
    context = {
        "form": form,
        "userForm": userForm,
        "dealer": dealerQs
    }
    return render(request, "accounts/farmerProfile.html", context)


@login_required
@customer_required
def Customer_Profile_View(request):
    customerQs = Customer.objects.get(user=request.user)
    form = CustomerProfileUpdateForm(instance=customerQs)
    userForm = UserUpdateForm(instance=request.user)
    if request.method == "POST":
        form = CustomerProfileUpdateForm(
            request.POST or None,
            request.FILES or None,
            instance=customerQs)
        userForm = UserUpdateForm(
            request.POST or None,
            request.FILES or None,
            instance=request.user)
        if form.is_valid() and userForm.is_valid():
            form.save()
            userForm.save()
            messages.success(request, "Profile successfully updated.")
            return HttpResponseRedirect("/accounts/customer/profile/")

    context = {
        "form": form,
        "userForm": userForm,
        "customerQs": customerQs
    }
    return render(request, "accounts/customerProfile.html", context)


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return render(request, 'accounts/activate_success.html')
    else:
        return render(request, 'accounts/activate_fail.html')


def administrator_Profile_View(request):
    context = {

    }
    return render(request, "accounts/administratorProfile.html", context)

old/farmers/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from accounts.models import Dealer, User, Rating, Product
from farmers.filters import OrderFilter
from farmers.forms import ProductAddForm, FarmerCategoryForm
from farmers.models import ProductCategory
from accounts.decorators import customer_required, dealer_required
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages


def homeView(request):
    dealerQs = Dealer.objects.all().order_by("?")
    dealers_count = (Dealer.objects.values(
        'category').count())

    categoriesQuery = ProductCategory.objects.all()
    orderFilter = OrderFilter(request.GET, queryset=dealerQs)
    context = {
        "dealers_count": dealers_count,
        "filter": orderFilter,
        "categories": categoriesQuery
    }
    return render(request, "farmers/home.html", context)


def CategoryFilterView(request, category):
    dealerQs = Dealer.objects.filter(
        category__category=category
    ).order_by("?")
    categoriesQuery = ProductCategory.objects.all()
    orderFilter = OrderFilter(request.GET, queryset=dealerQs)
    dealers_count = (Dealer.objects.values(
        'category').count())
    context = {
        "filter": orderFilter,
        "categories": categoriesQuery,
        "dealers_count": dealers_count
    }
    return render(request, "farmers/categoryFilter.html", context)


def SupportView(request):
    context = {

    }
    return render(request, "farmers/support.html", context)


@login_required
@dealer_required
def productAddView(request):
    dealerQs = Dealer.objects.get(user=request.user)
    form = ProductAddForm()
    category = dealerQs.category
    initial_data = {
        "category": category,
    }
    categoryForm = FarmerCategoryForm(initial=initial_data)

    if request.method == "POST":
        form = ProductAddForm(request.POST, request.FILES)
        if form.is_valid():
            qsForm = form.save(commit=False)
            qsForm.farmer = dealerQs
            qsForm.category = dealerQs.category
            qsForm.save()
            messages.success(request, "The product was successfully added.")
            return HttpResponseRedirect("/post/products/")
        else:
            form = ProductAddForm()
    context = {
        "form": form,
        "dealer": dealerQs,
        "catForm": categoryForm

    }
    return render(request, "farmers/product_add.html", context)


def dealersDetailsView(request, username):
    dealerQs = Dealer.objects.get(
        user__username=username
    )
    context = {
        "dealer": dealerQs
    }
    return render(request, "farmers/dealerDetails.html", context)


@login_required
@customer_required
def rateFarmer(request):
    if request.method == "POST":
        customer_id = request.POST.get('customer_id')
        el_id = request.POST.get('el_id')
        val = request.POST.get('val')

        # get the dealer
        dealer = Dealer.objects.get(pk=el_id)

        # update a rating instance
        try:
            obj = Rating.objects.get(Q(dealer=dealer),
                                     Q(customer=request.user))

            obj.rate = val
            obj.save()
        except Rating.DoesNotExist:
            # create a rating
            obj = Rating(dealer=dealer, customer=request.user, rate=val)
            obj.save()
        return JsonResponse(
            {
                "Success": "true", "rate": val
            }, safe=False
        )
    return JsonResponse({"success": "false"})

old/templates/farmers/categoryFilter.html
{%extends 'accounts/base.html'%}
<!---->
{% load widget_tweaks %} {%load crispy_forms_tags%}
<!---->
{%load static%} {%load humanize%}
<!---->
{%block title%} Farmers Listing {%endblock%}
<!---->
{%block category%}
<section class="ftco-section ftco-no-pt ftco-no-pb">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="category-wrap">
          <div
            class="card-header"
            style="background-color: forestgreen; color: white"
          >
            <a class="text-white">BROWSE BY <b>CATEGORY</b></a>
          </div>
          <div
            class="row no-gutters flex-row flex-nowrap"
            style="overflow-x: auto; white-space: normal"
          >
            <!--====================-->
            <div class="col-md-2" style="display: inline-block; float: none">
              <div class="top-category text-center no-border-left">
                <a href="{%url 'farmers:home'%}">
                  <span class="icon">
                    <img
                      src="{%static 'images/all.png'%}"
                      height="60px"
                      width="60px"
                    />
                  </span>

                  <p>
                    <span class="badge badge-sm badge-warning"
                      ><b>{{dealers_count}}</b></span
                    ><br />
                    <span><b>All</b></span>
                  </p></a
                >
              </div>
            </div>
            {%for category in categories%}
            <div class="col-md-2" style="display: inline-block; float: none">
              <div class="top-category text-center no-border-left">
                <a href="{%url 'farmers:categoryFilter' category.category%}">
                  <span class="icon">
                    <img
                      src="{{category.crop_icon.url}}"
                      height="60px"
                      width="60px"
                    />
                  </span>

                  <p>
                    <span class="badge badge-sm badge-warning"><b></b></span
                    ><br />
                    <span><b>{{category.category}}</b></span>
                  </p></a
                >
              </div>
            </div>
            {%endfor%}

            <!---->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{%endblock%} {%block content%}

<div class="row">
  {%for dealer in filter.qs%}
  <div class="col-sm-12 ftco-animate">
    <div
      class="job-post-item p-4 d-block d-lg-flex align-items-center"
      align="center"
    >
      <!---->

      <div class="col-sm-12">
        <div class="row">
          <div class="col-sm-3">
            <div class="img">
              <img
                class="rounded-circle"
                src="{{dealer.profile_picture.url}}"
                height="180px"
                width="180px"
                alt=""
              />
            </div>
          </div>
          <div class="col-sm-9">
            <div class="text pl-md-4 text-left">
              <span class="location mb-0 text-dark"
                ><span class="icon-my_location"></span>
                {{dealer.county|title}}, Kenya
              </span>
              <h2>
                <i class="fa fa-user fa-sm text-muted"></i>
                {{dealer.user.full_name|title}}
              </h2>
              <span class="position"
                ><i class="fa fa-tag fa-rotate-90"></i>
                {{dealer.category.category|title}}
              </span>
              <p class="mb-2 text-dark">
                {{dealer.bio|title|truncatewords:15}}
              </p>
              <span class="seen text-dark"
                ><i class="fa fa-clock-o"></i> Joined
                {{dealer.user.timestamp|timesince}} ago</span
              >
              <p>
                <a href="{%url 'farmers:dealersDetails' dealer.user.username%}">
                  <button
                    class="btn btn-md text-white mt-3"
                    style="background-color: #206dfb"
                    type="submit"
                  >
                    View Farmer
                  </button></a
                >
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {%endfor%}
</div>
{%endblock%} {%block side%}

<div class="sidebar-box bg-white p-4 ftco-animate">
  <h3 class="heading-sidebar">Browse By Category</h3>
  <form action="#" class="search-form mb-3">
    <div class="form-group">
      <span class="icon icon-search"></span>
      <input type="text" class="form-control" placeholder="Search..." />
    </div>
  </form>
  <form method="get" action="" class="browse-form">
    {{filter.form.category}}
    <button
      class="btn btn-sm text-white mt-2"
      style="background-color: #206dfb"
      type="submit"
    >
      Filter
    </button>
  </form>
</div>

<div class="sidebar-box bg-white p-4 ftco-animate">
  <h3 class="heading-sidebar">Browse By Location</h3>
  <form action="#" class="search-form mb-3">
    <div class="form-group">
      <span class="icon icon-search"></span>
      <input type="text" class="form-control" placeholder="Search..." />
    </div>
  </form>
  <div style="height: 350px; overflow-y: scroll">
    <form method="get" action="" class="browse-form">
      {{filter.form.county}}
      <button
        class="btn btn-sm text-white mt-2"
        style="background-color: #206dfb"
        type="submit"
      >
        Filter
      </button>
    </form>
  </div>
</div>

<div class="sidebar-box bg-white p-4 ftco-animate">
  <h3 class="heading-sidebar">Browse By Response Time</h3>
  <form action="#" class="search-form mb-3">
    <div class="form-group">
      <span class="icon icon-search"></span>
      <input type="text" class="form-control" placeholder="Search..." />
    </div>
  </form>
  <form method="get" action="" class="browse-form">
    {{filter.form.response}}
    <button
      class="btn btn-sm text-white mt-2"
      style="background-color: #206dfb"
      type="submit"
    >
      Filter
    </button>
  </form>
</div>

{%endblock%}

old/templates/farmers/home.html
{%extends 'accounts/base.html'%}
<!---->
{% load widget_tweaks %} {%load crispy_forms_tags%}
<!---->
{%load static%} {%load humanize%}
<!---->
{%block title%} Farmers Listing {%endblock%}
<!---->
{%block category%}
<section class="ftco-section ftco-no-pt ftco-no-pb">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="category-wrap">
          <div
            class="card-header"
            style="background-color: forestgreen; color: white"
          >
            <a class="text-white">BROWSE BY <b>CATEGORY</b></a>
          </div>
          <div
            class="row no-gutters flex-row flex-nowrap"
            style="overflow-x: auto; white-space: normal"
          >
            <!--====================-->
            <div class="col-md-2">
              <div class="top-category text-center no-border-left">
                <a href="{%url 'farmers:home'%}">
                  <span class="icon">
                    <img
                      src="{%static 'images/all.png'%}"
                      height="60px"
                      width="60px"
                    />
                  </span>

                  <p>
                    <span class="badge badge-md badge-warning">
                      <b>{{dealers_count}} </b> </span
                    ><br />
                    <span><b>All</b></span>
                  </p></a
                >
              </div>
            </div>
            {%for category in categories%}
            <div class="col-md-2" style="display: inline-block; float: none">
              <div class="top-category text-center no-border-left">
                <a href="{%url 'farmers:categoryFilter' category.category%}">
                  <span class="icon">
                    <img
                      src="{{category.crop_icon.url}}"
                      height="60px"
                      width="60px"
                    />
                  </span>

                  <p>
                    <span class="badge badge-sm badge-warning"><b></b></span
                    ><br />
                    <span><b>{{category.category}}lll</b></span>
                  </p></a
                >
              </div>
            </div>
            {%endfor%}

            <!---->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{%endblock%} {%block content%}

<div class="row">
  {%for dealer in filter.qs%}
  <div class="col-sm-12 ftco-animate">
    <div
      class="job-post-item p-4 d-block d-lg-flex align-items-center"
      align="center"
    >
      <!---->
      <div class="col-sm-12">
        <div class="row">
          <div class="col-sm-3">
            <div class="img">
              <img
                class="rounded-circle"
                src="{{dealer.profile_picture.url}}"
                height="180px"
                width="180px"
                alt=""
              />
            </div>
          </div>
          <div class="col-sm-9">
            <div class="text pl-md-4 text-left">
              <span class="location mb-0 text-dark"
                ><span class="icon-my_location"></span>
                {{dealer.county|title}}, Kenya
              </span>
              <h2>
                <i class="fa fa-user fa-sm text-muted"></i>
                {{dealer.user.full_name|title}}
              </h2>
              <span class="position"
                ><i class="fa fa-tag fa-rotate-90"></i>
                {{dealer.category.category|title}}
              </span>
              <p class="mb-2 text-dark">
                {{dealer.bio|title|truncatewords:15}}
              </p>
              <span class="seen text-dark"
                ><i class="fa fa-clock-o"></i> Joined
                {{dealer.user.timestamp|timesince}} ago
              </span>
              <p>
                <a href="{%url 'farmers:dealersDetails' dealer.user.username%}">
                  <button
                    class="btn btn-md text-white mt-3"
                    style="background-color: #206dfb"
                    type="submit"
                  >
                    View Farmer
                  </button></a
                >
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {%endfor%}
</div>
{%endblock%} {%block side%}

<div class="sidebar-box bg-white p-4 ftco-animate">
  <h3 class="heading-sidebar">Browse By Category</h3>
  <form action="#" class="search-form mb-3">
    <div class="form-group">
      <span class="icon icon-search"></span>
      <input type="text" class="form-control" placeholder="Search..." />
    </div>
  </form>
  <form method="get" action="" class="browse-form">
    {{filter.form.category}}
    <button
      class="btn btn-sm text-white mt-2"
      style="background-color: #206dfb"
      type="submit"
    >
      Filter
    </button>
  </form>
</div>

<div class="sidebar-box bg-white p-4 ftco-animate">
  <h3 class="heading-sidebar">Browse By Location</h3>
  <form action="#" class="search-form mb-3">
    <div class="form-group">
      <span class="icon icon-search"></span>
      <input type="text" class="form-control" placeholder="Search..." />
    </div>
  </form>
  <div style="height: 350px; overflow-y: scroll">
    <form method="get" action="" class="browse-form">
      {{filter.form.county}}
      <button
        class="btn btn-sm text-white mt-2"
        style="background-color: #206dfb"
        type="submit"
      >
        Filter
      </button>
    </form>
  </div>
</div>

<div class="sidebar-box bg-white p-4 ftco-animate">
  <h3 class="heading-sidebar">Browse By Response Time</h3>
  <form action="#" class="search-form mb-3">
    <div class="form-group">
      <span class="icon icon-search"></span>
      <input type="text" class="form-control" placeholder="Search..." />
    </div>
  </form>
  <form method="get" action="" class="browse-form">
    {{filter.form.response}}
    <button
      class="btn btn-sm text-white mt-2"
      style="background-color: #206dfb"
      type="submit"
    >
      Filter
    </button>
  </form>
</div>

{%endblock%} {% comment %} style="display: inline-block" {% endcomment %}