config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("modules.accounts.urls")),
    path("", include("modules.inventory.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]


admin.site.site_header = "Dj Starter Admin"
admin.site.site_title = "Dj Starter Admin Portal"
admin.site.index_title = "Welcome to Dj Starter Portal"

modules/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from modules.accounts.views import CustomerSignupView, FarmerSignupView
from modules.accounts import views

app_name = "accounts"

urlpatterns = [
    path(
        "login/",
        auth_views.LogoutView.as_view(
            template_name="accounts/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="accounts/logout.html",
        ),
        name="logout",
    ),
    path("farmer/signup/", FarmerSignupView.as_view(), name="farmerSignup"),
    path("signup/", CustomerSignupView.as_view(), name="customerSignup"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            success_url="/accounts/password_reset/done/",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="accounts/password_reset_subject.txt",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/reset/done/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("farmer/profile/", views.FarmerProfileView, name="farmerProfile"),
    path("customer/profile/", views.CustomerProfileView, name="customerProfile"),
]

modules/inventory/urls.py
from django.urls import path
from modules.inventory import views

app_name = "farmers"

urlpatterns = [
    path("", views.HomeView, name="home"),
]

old/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views
from accounts.views import dealerSignupView, adminSignupView, customerSignupView

app_name = "accounts"
urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
    path("signup/", dealerSignupView.as_view(), name="dealerSignup"),
    path("customer/signup/", customerSignupView.as_view(), name="customerSignup"),
    path("administrator/signup/", adminSignupView.as_view(), name="adminSignup"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    # Password Reset
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            success_url="/accounts/password_reset/done/",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="accounts/password_reset_subject.txt",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/reset/done/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # Profile
    path("farmer/profile/", views.Farmer_Profile_View, name="farmerProfile"),
    path("customer/profile/", views.Customer_Profile_View, name="customerProfile"),
    path(
        "administrator/profile/",
        views.administrator_Profile_View,
        name="administratorProfile",
    ),
]

old/farmers/urls.py
from django.urls import path
from farmers import views

app_name = "farmers"

urlpatterns = [
    path("", views.homeView, name="home"),
    path("post/products/", views.productAddView, name="product_add"),
    path("farmer/<username>/details/",
         views.dealersDetailsView, name="dealersDetails"),
    path(
        "category/<str:category>/",
        views.CategoryFilterView, name="categoryFilter"
    ),
    path('farmer/rating', views.rateFarmer, name="rateFarmer"),
]

old/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("farmers.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modules/inventory/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from modules.accounts.models import Farmer, FarmProductCategory


# Create your models here.
class Product(models.Model):
    product_name = models.CharField(_("product name"), max_length=156)
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE)
    quantity = models.FloatField(
        default=0.00,
        help_text="Number of Kgs available",
    )
    image = models.ImageField(upload_to="products/%y%m/%d")
    price = models.FloatField(_("price"), default=0.00)
    is_verified = models.BooleanField(_("is_verified"), default=True)
    description = models.TextField(_("description"), blank=True, null=True)
    on_stock = models.BooleanField(_("on stock"), default=True)
    category = models.ForeignKey(
        FarmProductCategory,
        on_delete=models.DO_NOTHING,
    )

    def __str__(self):
        return self.product_name

    class Meta:
        verbose_name_plural = "Farm Products"

modules/accounts/api/views.py
import requests

from django.contrib.auth import get_user_model
from modules.accounts.permissions import IsSuperUser
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.viewsets import ModelViewSet
from rest_framework_simplejwt.tokens import RefreshToken

from rest_framework_simplejwt.exceptions import InvalidToken, TokenError
from django.core.exceptions import ValidationError
from modules.accounts.api.serializers import (
    LoginSerializer,
    RegisterSerializer,
    UserSerializer,
)
from django.core.validators import validate_email


User = get_user_model()


class LoginViewSet(ModelViewSet, TokenObtainPairView):
    """
    API endpoint for user login and obtaining access and refresh tokens.
    """

    serializer_class = LoginSerializer
    permission_classes = [AllowAny]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data, context={"request": request}
        )
        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])
        except ValidationError as e:
            return Response(
                {"error": e.args[0]},
                status=status.HTTP_400_BAD_REQUEST,
            )
        return Response(serializer.validated_data, status=status.HTTP_200_OK)


class LogoutViewSet(ModelViewSet):
    """
    Logout view to invalidate the user's refresh token.
    """

    permission_classes = [IsAuthenticated]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        refresh_token = request.data.get("refresh_token")

        if not refresh_token:
            return Response(
                {"error": "Refresh token is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            # Blacklist the refresh token, making it invalid
            token = RefreshToken(refresh_token)
            token.blacklist()
            return Response(
                {"success": "User was successfully logged out."},
                status=status.HTTP_200_OK,
            )
        except Exception as e:
            return Response(
                {"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )


class RefreshViewSet(ModelViewSet, TokenRefreshView):
    """
    Endpoint allows all users to refresh their token,
    by passing the refresh token in order to get a new access token
    """

    permission_classes = (AllowAny,)
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)

        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])

        return Response(serializer.validated_data, status=status.HTTP_200_OK)


class RegisterViewSet(ModelViewSet):
    """
    ViewSet for user registration.

    Allows users to register by providing necessary information
    such as phone number, email, name, and password.
    """

    serializer_class = RegisterSerializer
    permission_classes = [AllowAny]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        context = {"request": request}
        serializer = self.get_serializer(data=request.data, context=context)
        serializer.is_valid(raise_exception=True)

        try:
            user = serializer.save()
            refresh = RefreshToken.for_user(user)

            response_data = {
                "user": serializer.data,
                "access_token": str(refresh.access_token),
                "refresh_token": str(refresh),
            }

            return Response(response_data, status=status.HTTP_201_CREATED)
        except ValidationError as e:
            return Response(
                {"error": str(e)},
                status=status.HTTP_400_BAD_REQUEST,
            )


# Google Login
# https://www.googleapis.com/auth/userinfo.email
# https://developers.google.com/oauthplayground/
class GoogleSocialLoginViewSet(ModelViewSet):
    """
    Google Social Login, Use the url below to test the endpoint;
    https://www.googleapis.com/auth/userinfo.email
    https://developers.google.com/oauthplayground/
    return access_token from the url above
    """

    permission_classes = [AllowAny]
    http_method_names = ["post"]

    def create(self, request, *args, **kwargs):
        token = request.data.get("token")

        if not token:
            return Response(
                {"error": "Token is required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            response = requests.get(
                "https://www.googleapis.com/oauth2/v2/userinfo",
                params={"access_token": token},
            )
            response.raise_for_status()
            response_data = response.json()

            email = response_data.get("email")
            if not email:
                return Response(
                    {"error": "Email not provided by Google"},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            # Validate email address format
            try:
                validate_email(email)
            except ValidationError:
                return Response(
                    {"error": "Invalid email address"},
                    status=status.HTTP_400_BAD_REQUEST,
                )

            user, created = User.objects.get_or_create(email=email)
            if created:
                user.full_name = response_data.get("name", "")
                user.is_active = True
                user.set_unusable_password()
                user.save()

            token = RefreshToken.for_user(user)
            return Response(
                {
                    "refresh": str(token),
                    "access": str(token.access_token),
                },
                status=status.HTTP_200_OK,
            )
        except requests.HTTPError as e:
            return Response(
                {"error": f"Google API request failed: {e.response.text}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )


class UserViewSet(ModelViewSet):
    """
    API endpoint that allows users to be viewed, created, updated, or deleted.
    """

    serializer_class = UserSerializer
    queryset = User.objects.all()
    permission_classes = [IsAuthenticated, IsSuperUser]
    http_method_names = ["get", "post", "put", "patch", "delete"]

modules/inventory/views.py
from django.shortcuts import render

from modules.accounts.models import FarmProductCategory, Farmer
from modules.inventory.filters import FarmerFilter

# Create your views here.


def HomeView(request):
    farmer = Farmer.objects.all().order_by("?")
    farmers_count = Farmer.objects.values("specialization").count()
    product_category = FarmProductCategory.objects.all()
    farmerFilter = FarmerFilter(request.GET, queryset=farmer)
    context = {
        "dealers_count": farmers_count,
        "filter": farmerFilter,
        "categories": product_category,
    }
    return render(request, "farmers/home.html", context)

modules/templates/includes/category.html
<section class="ftco-section ftco-no-pt ftco-no-pb">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="category-wrap" style="border-radius: 35px">
          <div
            class="card-header"
            style="background-color: forestgreen; color: white"
          >
            <a class="text-white">BROWSE BY <b>CATEGORY</b></a>
            <a href="" class="fa fa-list text-white float-right"></a>
          </div>
          <div class="row no-gutters">
            <div class="col-md-2">
              <div class="top-category text-center no-border-left">
                <a href=""
                  ><h3></h3>
                  <!-- <span class="icon flaticon-contact"></span> -->
                  <i
                    class="fa fa-spinne fa-pulse fa-3x"
                    style="color: #ff8b00"
                  ></i>
                  <p><span class="number"></span> <span>Suppliers</span></p></a
                >
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

modules/templates/includes/footer.html
{%load static%}
<footer class="ftco-footer ftco-bg-dark ftco-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Rackey Products Board</h2>
          <p>
            Never worry about sales or income from outbound channels with Rackey
            your farm is directly connected to thousands of customers interested
            in your products.
          </p>
          <ul
            class="ftco-footer-social list-unstyled float-md-left float-lft mt-3"
          >
            <li class="ftco-animate">
              <a href="#"><span class="icon-twitter"></span></a>
            </li>
            <li class="ftco-animate">
              <a href="#"><span class="icon-facebook"></span></a>
            </li>
            <li class="ftco-animate">
              <a href="#"><span class="icon-instagram"></span></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Farmers</h2>
          <ul class="list-unstyled">
            <li>
              <a href="{%url 'farmers:product_add'%}" class="pb-1 d-block"
                >Post a Product</a
              >
            </li>
            <li>
              <a href="{%url 'accounts:farmerProfile'%}" class="pb-1 d-block"
                >My Profile</a
              >
            </li>
            <li>
              <a href="{%url 'accounts:dealerSignup'%}" class="pb-1 d-block"
                >Farmer Signup</a
              >
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4 ml-md-4">
          <h2 class="ftco-heading-2">Customers</h2>
          <ul class="list-unstyled">
            <li>
              <a href="" class="pb-1 d-block">Browse Products</a>
            </li>
            <li>
              <a href="{%url 'accounts:customerProfile'%}" class="pb-1 d-block"
                >My Profile</a
              >
            </li>
            <li>
              <a href="{%url 'accounts:customerSignup'%}" class="pb-1 d-block"
                >Customer Signup</a
              >
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4 ml-md-4">
          <h2 class="ftco-heading-2">Account</h2>
          <ul class="list-unstyled">
            <li>
              <a href="" class="pb-1 d-block">My Account</a>
            </li>
            <li>
              <a href="{%url 'accounts:login'%}" class="pb-1 d-block"
                >Sign In</a
              >
            </li>
            <li>
              <a href="{%url 'accounts:dealerSignup'%}" class="pb-1 d-block"
                >Create Account</a
              >
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Have a Questions?</h2>
          <div class="block-23 mb-3">
            <ul>
              <li>
                <span class="icon icon-map-marker"></span
                ><span class="text">Taita Taveta University, Voi, Kenya</span>
              </li>
              <li>
                <a href="tel:0700215645"
                  ><span class="icon icon-phone"></span
                  ><span class="text">+254700215645</span></a
                >
              </li>
              <li>
                <a href="mailto:raki@gmail.com"
                  ><span class="icon icon-envelope"></span
                  ><span class="text">rackey@gmail.com</span></a
                >
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">
        <p>
          Copyright &copy; 2022 Rackey, Powered by
          <a href="https://coderpass.herokuapp.com" target="_blank"
            >CoderPass</a
          >
        </p>
      </div>
    </div>
  </div>
</footer>

modules/templates/includes/nav.html
{%load static%}
<nav
  class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light"
  id="ftco-navbar"
>
  <div class="container-fluid px-md-4">
    <a class="navbar-brand" href="">Agrinvest</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#ftco-nav"
      aria-controls="ftco-nav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="oi oi-menu mr-2"></span>
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a
            
            {% comment %} href="{%url 'inventory:home'%}" {% endcomment %}
           
            class="nav-link text-white"
            ><i class="fa fa-home"></i> Home</a
          >
        </li>

        <li class="nav-item">
          <a href="" class="nav-link text-white"
            ><i class="fa fa-phone-square"></i> Customer Support</a
          >
        </li>
        <li class="nav-item">
          <a href="" class="nav-link text-white"
            ><i class="fa fa-question-circle"></i> FAQ's</a
          >
        </li>

        {%if request.user.is_authenticated%}
        <!---->
        {%if request.user.role == "Customer"%}
        <li class="nav-item">
          <a
            href="{%url 'accounts:customerProfile'%}"
            class="nav-link text-white"
            ><i class="fa fa-user"></i> Profile</a
          >
        </li>
        {%elif request.user.role == "Dealer"%}
        <li class="nav-item">
          <a href="{%url 'accounts:farmerProfile'%}" class="nav-link text-white"
            ><i class="fa fa-user"></i> Profile</a
          >
        </li>
        {%endif%}
        <li class="nav-item">
          <a href="{%url 'accounts:logout'%}" class="nav-link text-white"
            ><i class="fa fa-sign-out"></i> Logout</a
          >
        </li>
        {%else%}
        <li class="nav-item">
          <a href="{%url 'accounts:farmerSignup'%}" class="nav-link text-white"
            ><i class="fa fa-pencil-square"></i> Register</a
          >
        </li>
        <li class="nav-item">
          <a href="{%url 'accounts:login'%}" class="nav-link text-white"
            ><i class="fa fa-sign-in"></i> Login</a
          >
        </li>
        {%endif%}
        <!---->

        {%if request.user.is_authenticated and request.user.role == "Customer"%}
        <li class="nav-item cta cta-colored">
          <a href="{%url 'farmers:home'%}" class="nav-link"> Want Products</a>
        </li>
        {%else%}
        <li class="nav-item cta mr-md-1 mr-3">
          <a
            
            {% comment %} href="{%url 'farmers:product_add'%}" {% endcomment %}
          
            class="nav-link"
            >Post Products</a
          >
        </li>
        {%endif%}
      </ul>
    </div>
  </div>
</nav>